name: eventflux
description: "Efficient handling of server-sent event streams with easy connectivity and data management."
version: 2.1.2
homepage: https://gokula.dev
repository: https://github.com/Imgkl/EventFlux
issue_tracker: https://github.com/Imgkl/EventFlux/issues
topics: [sse, server-sent-events, streaming-events]
screenshots:
 - description: 'The EventFlux Logo'
   path: screenshot/logo.webp

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

platforms:
  android:
  ios:
  macos:
  linux:
  windows:


  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
